#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr .data
#' @importFrom dplyr all_of
#' @importFrom dplyr coalesce
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr relocate
#' @importFrom dplyr select
#' @importFrom glue glue
#' @importFrom purrr walk
#' @importFrom readr read_csv
#' @importFrom rlang :=
#' @importFrom rlang .data
#' @importFrom rlang abort
#' @importFrom rlang as_name
#' @importFrom rlang ensym
#' @importFrom stats quantile
#' @importFrom tibble tribble
#' @importFrom tidyr pivot_wider
#' @importFrom tidyselect all_of
#' @importFrom tidyselect any_of
#' @importFrom tiltIndicator categorize_risk
#' @importFrom tiltIndicator epa_at_company_level
#' @importFrom tiltIndicator epa_compute_profile_ranking
#' @importFrom tiltIndicator insert_row_with_na_in_risk_category
#' @importFrom tiltIndicator nest_levels
#' @importFrom tiltIndicator spa_compute_profile_ranking
#' @importFrom tiltIndicator tilt_profile
#' @importFrom tiltIndicator unnest_company
#' @importFrom tiltIndicator unnest_product
#' @importFrom tiltIndicatorAfter profile_emissions
#' @importFrom tiltIndicatorAfter profile_sector
#' @importFrom tiltPolish rename_transition_risk_profile_cols_company
#' @importFrom tiltPolish rename_transition_risk_profile_cols_product
#' @importFrom tiltPolish rename_webtool_cols_at_company_level_wide
#' @importFrom tiltPolish select_webtool_cols_at_company_level_wide
#' @importFrom tiltPolish select_webtool_cols_at_product_level
#' @importFrom tiltToyData toy_ecoinvent_activities
#' @importFrom tiltToyData toy_ecoinvent_europages
#' @importFrom tiltToyData toy_ecoinvent_inputs
#' @importFrom tiltToyData toy_emissions_profile_any_companies
#' @importFrom tiltToyData toy_emissions_profile_products
#' @importFrom tiltToyData toy_emissions_profile_products_ecoinvent
#' @importFrom tiltToyData toy_emissions_profile_upstream_products
#' @importFrom tiltToyData toy_emissions_profile_upstream_products_ecoinvent
#' @importFrom tiltToyData toy_europages_companies
#' @importFrom tiltToyData toy_isic_name
#' @importFrom tiltToyData toy_sector_profile_any_scenarios
#' @importFrom tiltToyData toy_sector_profile_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_companies
#' @importFrom tiltToyData toy_sector_profile_upstream_products
#' @importFrom utils write.csv
#' @importFrom withr local_options
#' @importFrom withr local_seed
## usethis namespace: end
NULL
